```{r}
# data wrangling : first dataset
library(tidyverse)
library(readr)
library(leaflet)
library(viridis)
library(sf)
library(countrycode)
library(stringr)

# import first data set
soccer_data1 <- read_delim("data/transfermarkt_fbref_201718.csv", delim = ";", 
                           escape_double = FALSE, trim_ws = TRUE, show_col_types = FALSE)

# wrangle data
soccer_data2 <- soccer_data1 |>
  select(player, nationality, league) |>
    mutate(
    nationality = str_extract(nationality, "[a-z]{2}"),
    full_country_name = countrycode(nationality, "iso2c", "country.name", warn = TRUE))

# Create a mapping of unmatched values to placeholders
placeholder_mapping <- c(
  "en" = "England",
  "wa" = "Wales",
  "xk" = "Kosovo"
)

# Replace unmatched values based on the mapping
soccer_data2$full_country_name <- ifelse(
  is.na(soccer_data2$full_country_name),
  placeholder_mapping[soccer_data2$nationality],
  soccer_data2$full_country_name
)

#Filter the leagues
Premier_League <- soccer_data2 |>
  filter(league == "Premier League")

La_liga <- soccer_data2 |>
  filter(league == "La Liga")

Bundesliga <- soccer_data2 |>
  filter(league == "Bundesliga")

#Number of players from each country for every league
 Num_players_PremierLeague <- Premier_League |>
  group_by(full_country_name) |>
  summarise(num_players = n())
 
 Num_players_Laliga <- La_liga |>
  group_by(full_country_name) |>
  summarise(num_players = n())
 
 Num_players_Bundesliga <- Bundesliga |>
  group_by(full_country_name) |>
  summarise(num_players = n())
  

# save new data file
write.csv(soccer_data2, "wrangled_dataset.csv", row.names = FALSE)
```


```{r}
#PREMIER LEAGUE

#Create map object
 world_map1 <-  maps::map("world", plot = FALSE, fill = TRUE) |>
    st_as_sf()

# Draw map
 PremierLeague_map <- Num_players_PremierLeague |>
   left_join(world_map1, by = c("full_country_name"="ID"))
 
head(PremierLeague_map)

#Create a visualization

ggplot(PremierLeague_map, aes(geometry=geom, fill = num_players)) +
   geom_sf() +
   theme_void() +
   labs(fill = "Number of players"
       , title = "Premier League Map") +
   scale_fill_viridis(option = "magma", direction = -1) +
    coord_sf(lims_method = "geometry_bbox", default_crs = NULL)

```

```{r}
#LA LIGA

#Create map object
 world_map2 <-  maps::map("world", plot = FALSE, fill = TRUE) |>
    st_as_sf()

# Draw map
 La_liga_map <- Num_players_Laliga |>
   left_join(world_map2, by = c("full_country_name"="ID"))
 
head(La_liga_map)

#Create a visualization

ggplot(La_liga_map, aes(geometry=geom, fill = num_players)) +
   geom_sf() +
   theme_void() +
   labs(fill = "Number of players"
       , title = "La liga Map") +
   scale_fill_viridis(option = "magma", direction = -1) +
    coord_sf(lims_method = "geometry_bbox", default_crs = NULL)
```

```{r}
#BUNDESLIGA

#Create map object
 world_map3 <-  maps::map("world", plot = FALSE, fill = TRUE) |>
    st_as_sf()

# Draw map
 Bundesliga_map <- Num_players_Bundesliga |>
   left_join(world_map3, by = c("full_country_name"="ID"))
 
head(Bundesliga_map)

#Create a visualization

ggplot(Bundesliga_map, aes(geometry=geom, fill = num_players)) +
   geom_sf() +
   theme_void() +
   labs(fill = "Number of players"
       , title = "Bundesliga Map") +
   scale_fill_viridis(option = "magma", direction = -1) +
    coord_sf(lims_method = "geometry_bbox", default_crs = NULL)
```
